// Xavier O'Rourke, January 2019

flipTime = 200; // How many miliseconds it takes to half-flip a card
let allSymbols = [ // The names of the FontAwesome symbols which might appear on cards (origin.fontawesome.com/)
    "cat",
    "dog",
    "dove",
    "dragon",
    "feather-alt",
    "fish",
    "frog",
    "hippo",
    "horse",
    "balance-scale",
    "atom",
    "baby-carriage",
    "biohazard",
    "bug",
    "building",
    "book",
    "car-side",
    "carrot",
    "chess-knight",
    "chess-queen",
    "child",
    "code",
    "cogs",
    "cookie-bite",
    "cubes",
    "cut",
    "drum",
    "dungeon",
    "eye",
    "ghost",
    "globe-americas",
    "guitar",
    "heart",
    "home",
    "mountain",
    "palette",
    "paper-plane",
    "puzzle-piece",
    "seedling",
    "shapes",
    "skull",
    "smile-beam",
    "spa",
    "sun",
    "theater-masks",
    "thermometer-half",
    "toilet-paper",
    "tractor",
    "tools",
    "tree",
    "university",
    "cloud-moon",
]

var numCards = null;